### ISSUE TITLE
Panic when query result is empty or incomplete

### ISSUE THREAD

**Issue by apatters** [babolivier/go-doh-client#4]
I get the following panic if a query result message is empty (or too short):

```text
panic: runtime error: index out of range [2] with length 0
goroutine 6130 [running]:
github.com/babolivier/go-doh-client.parseResponse(0xc00f080600, 0x0, 0x200, 0x40, 0xc00f080600, 0x0, 0x200, 0x0)
	github.com/babolivier/go-doh-client@v0.0.0-20200723140836-2f86c709ac4a/response.go:46 +0x84f
github.com/babolivier/go-doh-client.(*Resolver).lookup(0xc009a41d20, 0xc001f61b60, 0x10, 0x1001c, 0x7fd3300600a0, 0x0, 0x203001, 0x0, 0x7fd3300600a0)
	github.com/babolivier/go-doh-client@v0.0.0-20200723140836-2f86c709ac4a/resolver.go:26 +0xd8
github.com/babolivier/go-doh-client.(*Resolver).LookupAAAA(0xc009a41d20, 0xc001f61b60, 0x10, 0x58, 0x8d0a40, 0x0, 0x0, 0x58, 0xc005834c00, 0x40f170, ...)
	github.com/babolivier/go-doh-client@v0.0.0-20200723140836-2f86c709ac4a/resolver.go:67 +0x7c
```

The resolver is sending back corrupt entries, but the package should issue an error instead of panicing.

**Comment by apatters** [comment]
Will do.
